### PR TITLE
#156958159 Fund transfer via wallet

### PR DESCRIPTION
**Pull request by Felglitzzz**
#### What does this PR do?
Integrates paystack payment as one of the payment options for users

#### Description of Task to be completed?
- Make a wallet schema in accout schema
- Include server methods to get balance of wallet

#### How should this be manually tested?

- npm run git clone `https://github.com/andela/nazgul-rc.git` to clone the repository
- navigate to the nazgul-rc folder
- run `curl https://install.meteor.com/ | sh`
- run `npm install -g reaction-cli`
- install dependencies with`meteor npm install`
- run `reaction` to start up server
- once app is running, navigate to localhost:3000
- navigate dropdown in mainpage and click on `wallet` to check wallet dashboard
- transfer funds to other users

#### What are the relevant pivotal tracker stories?
#156958159

#### Screenshots (if appropriate)
screen shot 2018-06-05 at 4 27 50 pm
screen shot 2018-06-05 at 4 27 58 pm
screen shot 2018-06-05 at 4 28 09 pm
screen shot 2018-06-05 at 4 28 16 pm

### CODE REVIEW

**Comment by morekoya** [comment]
What happens if the user changes the currency the site is using. Would it affect the currency of the money transferred?

**Comment by Felglitzzz** [comment]
@andela-morekoya, it won't affect it. I implemented naira. As such, if I change it in the application to Naira, the same money will still be transferred. The PO also talked about that in the last demo and I showed her how changing the currency from the admin settings board wouldn't change the amount of money being transferred.
Point is I am supposed to change it to naira before the demo tomorrow to make things uniform.

**Comment by morekoya** [comment]
In that case, won't it be better to be specific about the currency of the amount being transferred during confirmation? Your screenshot does not specify a currency.

**Comment by Felglitzzz** [comment]
Oh true, my bad. Implemented your feedback already and my review app is building

**Comment by morekoya** [comment]
Any reason for 
screen shot 2018-06-05 at 7 06 39 pm?
Why not just `transfer funds`?

**Comment by Felglitzzz** [comment]
Feedback Implemented

**Pull request merged**
